controllers/CategoryController.php
<?php

namespace app\controllers;
use Yii;
use app\models\Category;


class CategoryController extends \yii\web\Controller
{
    public function actionIndex()
    {
        $categories = Category::find()->all();

        return $this->render('index', [
            'categories' => $categories,
        ]);
    }

    public function actionCreate()
{
    $model = new Category();

    if ($model->load(Yii::$app->request->post()) && $model->validate()) {
        $category = new Category();
        $category->title = $model->title;
        $category->description = $model->description;

        if ($category->save()) {
            Yii::$app->session->setFlash('success', 'Category has been created successfully.');
            return $this->redirect(['create']);
        } else {
            Yii::$app->session->setFlash('error', 'Failed to save the category.');

        }
    }

    return $this->render('create', [
        'model' => $model,
    ]);
}

public function actionUpdate($id)
{
    $category = Category::findOne($id);

    if (!$category) {
        throw new \yii\web\NotFoundHttpException('Category not found.');
    }

    $model = new Category();
    $model->title = $category->title;
    $model->description = $category->description;

    if ($model->load(Yii::$app->request->post()) && $model->validate()) {
        $category->title = $model->title;
        $category->description = $model->description;


        if ($category->save()) {
            Yii::$app->session->setFlash('success', 'Category has been updated successfully.');
            return $this->redirect(['index']);
        } else {
            Yii::$app->session->setFlash('error', 'Failed to update the category.');
        }
    }

    return $this->render('update', [
        'model' => $model,
    ]);
}


}

controllers/ProductController.php
<?php

namespace app\controllers;
use Yii;
use app\models\Product;
use app\models\Image;
use yii\web\UploadedFile;

class ProductController extends \yii\web\Controller
{
    public function actionIndex()
    {
        $products = Product::find()->all();

        return $this->render('index', [
            'products' => $products,
        ]);
    }

    public function actionCreate()
    {
        $model = new Product();

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $product = new Product();
            $product->title = $model->title;
            $product->category_id = $model->category_id;
            $product->description = $model->description;

            // Handle image upload (you need to implement this)
            // Example: $product->image_id = $imageModel->id;
            if (Yii::$app->request->isPost) {
                $model->image = UploadedFile::getInstance($model, 'image');
            }

            // dd('sss',$model->title,$model->image);

            $image = $this->uploadImage($model->image);
            if ($image) {
                $product->image_id = $image->id;
            }
            if ($product->save()) {
                Yii::$app->session->setFlash('success', 'Product has been created successfully.');
                return $this->redirect(['index']);

            } else {
                Yii::$app->session->setFlash('error', 'Failed to save the product.');
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    public function actionUpdate($id)
    {
        $product = Product::findOne($id);

        if (!$product) {
            throw new \yii\web\NotFoundHttpException('Product not found.');
        }

        $model = new Product();
        $model->title = $product->title;
        $model->category_id = $product->category_id;
        $model->description = $product->description;

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $product->title = $model->title;
            $product->category_id = $model->category_id;
            $product->description = $model->description;
            $image = $this->uploadImage($model->image);
            if ($image) {
                $product->image_id = $image->id;
            }

            if ($product->save()) {
                Yii::$app->session->setFlash('success', 'Product has been updated successfully.');
                return $this->redirect(['index']);
            } else {
                Yii::$app->session->setFlash('error', 'Failed to update the product.');
            }
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    private function uploadImage($file)
        {
            if ($file) {
                $image = new Image();
                $image->title = $file->baseName;
                $image->name = $file->name;
                $image->path = 'uploads/' . $file->baseName . '.' . $file->extension;

                if ($file->saveAs($image->path) && $image->save()) {
                    return $image;
                }
            }

            return null;
        }


        public function getImage()
    {
        return $this->hasOne(Image::class, ['id' => 'image_id']);
    }

    // ... other methods ...

    // Setter for image_id attribute
    public function setImageId($value)
    {
        $this->image_id = $value;
    }

    // Getter for image_id attribute
    public function getImageId()
    {
        return $this->image_id;
    }

}

views/layouts/main.php
<?php

/** @var yii\web\View $this */
/** @var string $content */

use app\assets\AppAsset;
use app\widgets\Alert;
use yii\bootstrap5\Breadcrumbs;
use yii\bootstrap5\Html;
use yii\bootstrap5\Nav;
use yii\bootstrap5\NavBar;

AppAsset::register($this);

$this->registerCsrfMetaTags();
$this->registerMetaTag(['charset' => Yii::$app->charset], 'charset');
$this->registerMetaTag(['name' => 'viewport', 'content' => 'width=device-width, initial-scale=1, shrink-to-fit=no']);
$this->registerMetaTag(['name' => 'description', 'content' => $this->params['meta_description'] ?? '']);
$this->registerMetaTag(['name' => 'keywords', 'content' => $this->params['meta_keywords'] ?? '']);
$this->registerLinkTag(['rel' => 'icon', 'type' => 'image/x-icon', 'href' => Yii::getAlias('@web/favicon.ico')]);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>" class="h-100">
<head>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="d-flex flex-column h-100">
<?php $this->beginBody() ?>

<header id="header">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => ['class' => 'navbar-expand-md navbar-dark bg-dark fixed-top']
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
            ['label' => 'List Category', 'url' => ['/category/index']],
            ['label' => 'Create Category', 'url' => ['/category/create']],
            ['label' => 'List Product', 'url' => ['/product/index']],
            ['label' => 'Create Product', 'url' => ['/product/create']],
            Yii::$app->user->isGuest
                ? ['label' => 'Login', 'url' => ['/site/login']]
                : '<li class="nav-item">'
                    . Html::beginForm(['/site/logout'])
                    . Html::submitButton(
                        'Logout (' . Yii::$app->user->identity->username . ')',
                        ['class' => 'nav-link btn btn-link logout']
                    )
                    . Html::endForm()
                    . '</li>'
        ]
    ]);
    NavBar::end();
    ?>
</header>

<main id="main" class="flex-shrink-0" role="main">
    <div class="container">
        <?php if (!empty($this->params['breadcrumbs'])): ?>
            <?= Breadcrumbs::widget(['links' => $this->params['breadcrumbs']]) ?>
        <?php endif ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</main>

<footer id="footer" class="mt-auto py-3 bg-light">
    <div class="container">
        <div class="row text-muted">
            <div class="col-md-6 text-center text-md-start">&copy; My Company <?= date('Y') ?></div>
            <div class="col-md-6 text-center text-md-end"><?= Yii::powered() ?></div>
        </div>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>